### ISSUE TITLE
About the screenshot

### ISSUE THREAD

**Issue by prasoonmohan** [sarahshashmi/rps_game#2]
provide a screenshot of your rock paper scissors game

that will helps to see your wonderfull work without clone or dowload zip.

**Comment by sarahshashmi** [comment]
Sure. I will attach it.

**Comment by sarahshashmi** [comment]
[Screen-Recording](https://drive.google.com/drive/folders/1bP3GBzvG4mWid3-goIK6cRnjI0FVGk34?usp=sharing)

**Comment by prasoonmohan** [comment]
Thanks for considering ms sarah....
